//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Kfstorm.DoubanFM.Core.UnitTest {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Kfstorm.DoubanFM.Core.UnitTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;groups&quot;: [
        ///        {
        ///            &quot;chls&quot;: [
        ///                {
        ///                    &quot;style&quot;: {
        ///                        &quot;display_text&quot;: &quot;&quot;,
        ///                        &quot;bg_color&quot;: &quot;0x499884&quot;,
        ///                        &quot;layout_type&quot;: 1,
        ///                        &quot;bg_image&quot;: &quot;&quot;
        ///                    },
        ///                    &quot;intro&quot;: &quot;我的个性化音乐频道&quot;,
        ///                    &quot;name&quot;: &quot;私人&quot;,
        ///                    &quot;song_num&quot;: 123,
        ///                    &quot;collected&quot;: &quot;disabled&quot;,
        ///                    &quot;cover&quot;: &quot;http:\/\/img3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChannelListExample {
            get {
                return ResourceManager.GetString("ChannelListExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;warning&quot;:&quot;user_is_ananymous&quot;,&quot;r&quot;:0,&quot;version_max&quot;:100,&quot;is_show_quick_start&quot;:1,&quot;song&quot;:[{&quot;album&quot;:&quot;\/subject\/1982398\/&quot;,&quot;picture&quot;:&quot;http:\/\/img3.douban.com\/lpic\/s2338142.jpg&quot;,&quot;ssid&quot;:&quot;5292&quot;,&quot;artist&quot;:&quot;The Bird And The Bee&quot;,&quot;url&quot;:&quot;http:\/\/mr3.douban.com\/201504101620\/81e4f0e73bce5d935531d47617b074f9\/view\/song\/small\/p164666.mp4&quot;,&quot;company&quot;:&quot;EMI&quot;,&quot;title&quot;:&quot;Because&quot;,&quot;rating_avg&quot;:4.041,&quot;length&quot;:218,&quot;subtype&quot;:&quot;&quot;,&quot;public_time&quot;:&quot;2007&quot;,&quot;songlists_count&quot;:6,&quot;sid&quot;:&quot;164666&quot;,&quot;aid&quot;:&quot;1982398&quot;,&quot;sha256&quot;:&quot;42cd018f0016b9d21 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayList {
            get {
                return ResourceManager.GetString("PlayList", resourceCulture);
            }
        }
    }
}
