//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kfstorm.DoubanFM.Core.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kfstorm.DoubanFM.Core.UnitTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;groups&quot;: [
        ///        {
        ///            &quot;chls&quot;: [
        ///                {
        ///                    &quot;style&quot;: {
        ///                        &quot;display_text&quot;: &quot;&quot;,
        ///                        &quot;bg_color&quot;: &quot;0x499884&quot;,
        ///                        &quot;layout_type&quot;: 1,
        ///                        &quot;bg_image&quot;: &quot;&quot;
        ///                    },
        ///                    &quot;intro&quot;: &quot;我的个性化音乐频道&quot;,
        ///                    &quot;name&quot;: &quot;私人&quot;,
        ///                    &quot;song_num&quot;: 123,
        ///                    &quot;collected&quot;: &quot;disabled&quot;,
        ///                    &quot;cover&quot;: &quot;http:\/\/img3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChannelListExample {
            get {
                return ResourceManager.GetString("ChannelListExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;code&quot; : 123,
        ///    &quot;msg&quot; : &quot;Sample error&quot;,
        ///    &quot;path&quot; : &quot;sample/path&quot;
        ///}.
        /// </summary>
        internal static string ErrorResponseSample {
            get {
                return ResourceManager.GetString("ErrorResponseSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;r&quot; : 123,
        ///    &quot;err&quot; : &quot;Sample error&quot;
        ///}.
        /// </summary>
        internal static string ErrorResponseSample_OldApi {
            get {
                return ResourceManager.GetString("ErrorResponseSample_OldApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;warning&quot;: &quot;user_is_ananymous&quot;,
        ///    &quot;r&quot;: 0,
        ///    &quot;version_max&quot;: 100,
        ///    &quot;is_show_quick_start&quot;: 1,
        ///    &quot;song&quot;: [
        ///        {
        ///            &quot;picture&quot;: &quot;http:\/\/img3.douban.com\/view\/dale-online\/dale_ad\/public\/f8c88e7c33c0e37.jpg&quot;,
        ///            &quot;albumtitle&quot;: &quot;豆瓣FM&quot;,
        ///            &quot;adtype&quot;: 3,
        ///            &quot;monitor_url&quot;: &quot;&quot;,
        ///            &quot;album&quot;: &quot;http:\/\/erebor.douban.com\/redirect\/?ad=122410&amp;uid=&amp;bid=quklsdfso9A&amp;unit=dale_fm_audio&amp;ip=58.208.65.228&amp;crtr=4%3A17725&amp;mark=&amp;hn=gardner2&amp;sig=1391aadcce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayList {
            get {
                return ResourceManager.GetString("PlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;groups&quot;: [
        ///        {
        ///            &quot;chls&quot;: [
        ///                {
        ///                    &quot;style&quot;: {
        ///                        &quot;display_text&quot;: &quot;&quot;,
        ///                        &quot;bg_color&quot;: &quot;0x499884&quot;,
        ///                        &quot;layout_type&quot;: 1,
        ///                        &quot;bg_image&quot;: &quot;&quot;
        ///                    },
        ///                    &quot;intro&quot;: &quot;我的个性化音乐频道&quot;,
        ///                    &quot;name&quot;: &quot;私人&quot;,
        ///                    &quot;song_num&quot;: 123,
        ///                    &quot;collected&quot;: &quot;disabled&quot;,
        ///                    &quot;cover&quot;: &quot;http:\/\/img3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchChannelResultExample {
            get {
                return ResourceManager.GetString("SearchChannelResultExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;access_token&quot;: &quot;c908a1375d9e74bc5b19e3a618db5e34&quot;,
        ///	&quot;douban_user_name&quot;: &quot;K.F.Storm&quot;,
        ///	&quot;douban_user_id&quot;: &quot;49549004&quot;,
        ///	&quot;expires_in&quot;: 604800,
        ///	&quot;refresh_token&quot;: &quot;b92fa09e3d59022b2b8ee1dab80b0681&quot;
        ///}.
        /// </summary>
        internal static string TestOAuthResponse {
            get {
                return ResourceManager.GetString("TestOAuthResponse", resourceCulture);
            }
        }
    }
}
